<?php

require_once dirname(__FILE__) . '/../../seoimpl/pseo-impl.php';

/**
 * Test class for PSeoImpl.
 * Generated by PHPUnit on 2012-04-07 at 03:38:22.
 */
class PSeoImplTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PSeoImpl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PSeoImpl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddMeta().
     */
    public function testAddMeta() {
        $this->object->addMeta('title', 'test title');
        $this->assertEquals('test title', $this->object->getMeta('title'));
    }

    /**
     */
    public function testAddjs() {
        $this->object->addjs('jsfile.js');
        $this->assertTrue($this->object->isAddedJs('jsfile.js'));
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testEchoJs().
     */
    public function testEchoJs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @depends testAddMeta
     */
    public function testEchoMeta() {
        $this->object->addMeta('title', 'Test title');
        $this->object->addMeta('description', 'Test description');
        $output = $this->object->echoMeta();
        $this->assertTrue(FALSE !== strpos($output, '<meta name="title"'));
        $this->assertTrue(FALSE !== strpos($output, '<meta name="description"'));
    }

}

?>
